[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "task-adapter"
version = "0.0"
description = ""
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
]

dependencies = [
]

[tool.setuptools.packages.find]
exclude = ["assets*", "benchmark*"]

[tool.wheel]
exclude = ["assets*", "benchmark*"]
